import React, { useState } from 'react';
import { DashboardLayout } from '../layouts/DashboardLayout';
import { Card, Button } from '../components/ui';
import ReactMarkdown from 'react-markdown';
import { FileText, Download, Share2 } from 'lucide-react';
import { useEffect } from "react";
import { reportsService } from "../services/reports";
import { formatDateTime } from "../utils/dateFormatter";

function extractSection(text, title) {
  if (!text) return "";
  const sections = text.split("# ");
  const section = sections.find(s =>
    s.startsWith(title)
  );
  if (!section) return "";
  return section.replace(title, "").trim();
}

export function Reports() {
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(true);

  const loadReport = async () => {
    setLoading(true);

    try {
      const data = await reportsService.getExecutiveReport();
      setReport(data);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadReport();
  }, []);

  const executiveSummary =
    extractSection(report?.ai_report, "Executive Summary");

  const threatAssessment =
    extractSection(report?.ai_report, "Threat Assessment");

  const businessImpact =
    extractSection(report?.ai_report, "Business Impact");

  const recommendations =
    extractSection(report?.ai_report, "Recommendations");

  return (
    <DashboardLayout>
      <div className="pb-2 border-b border-slate-800 flex items-center justify-between">
        <div>
          <div className="flex items-center gap-2">
            <FileText className="w-6 h-6 text-cyan-400" />
            <h1 className="text-2xl font-bold text-slate-100 tracking-tight">Gemini AI Intelligence Reports Repository</h1>
          </div>
          <p className="text-xs text-slate-400 mt-1">
            Archived case files, executive briefs, and customer notification transcripts generated by LLM pipeline.
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        <div className="lg:col-span-4 space-y-4">

          <Card>
            <h3 className="text-sm font-semibold">
              Overall Risk
            </h3>
            <div
              className={`text-3xl font-bold mt-2 ${report?.overall_risk === "LOW"
                ? "text-emerald-400"
                : report?.overall_risk === "MEDIUM"
                  ? "text-yellow-400"
                  : "text-red-400"
                }`}
            >
              {report?.overall_risk ?? "-"}
            </div>
          </Card>

          <Card>
            <h3 className="text-sm font-semibold">
              Fraud Rate
            </h3>
            <div className="text-3xl font-bold text-red-400 mt-2">
              {report?.fraud_rate}%
            </div>
          </Card>

          <Card>
            <h3 className="text-sm font-semibold">
              Transactions
            </h3>
            <div className="text-3xl font-bold text-emerald-400 mt-2">
              {report?.total_transactions}
            </div>
          </Card>

          <Card>
            <h3 className="text-sm font-semibold">
              AI Engine
            </h3>
            <div className="mt-3 flex items-center gap-2">
              <div className="w-3 h-3 rounded-full bg-emerald-400 animate-pulse" />
              <span className="text-emerald-400 font-semibold">
                Gemini 2.5 Flash Online
              </span>
              <span className="text-xs px-2 py-1 rounded bg-emerald-500/10 text-emerald-400">
                ONLINE
              </span>
            </div>
          </Card>

          <Card>
            <h3 className="text-sm font-semibold">
              Last Generated
            </h3>
            <div className="mt-3 text-slate-300">
              {report?.generated_at
                ? formatDateTime(report.generated_at)
                : "-"}
            </div>
          </Card>

        </div>

        {/* Right: Markdown Viewer */}
        <div className="lg:col-span-8">
          <Card
            glass
            title="AI Executive Intelligence Report"
            subtitle="Generated automatically by FinGuard AI + Gemini"
            action={
              <div className="flex gap-2">

                <Button
                  variant="secondary"
                  size="sm"
                  onClick={loadReport}
                >
                  Refresh
                </Button>

                <Button
                  variant="secondary"
                  size="sm"
                  onClick={() => navigator.clipboard.writeText(window.location.href)}
                >
                  <Share2 size={14} className="mr-1" />
                  Share
                </Button>

                <Button
                  variant="outline"
                  size="sm"
                  disabled
                >
                  <Download size={14} className="mr-1" />
                  Export PDF
                </Button>

              </div>
            }
          >
            <div className="p-4 rounded-xl bg-slate-950/80 border border-slate-800 max-h-[600px] overflow-y-auto markdown-body">
              {loading ? (
                <div className="py-20 text-center text-slate-400">
                  <div className="py-24 flex flex-col items-center justify-center">

                    <div className="w-10 h-10 rounded-full border-4 border-cyan-500 border-t-transparent animate-spin" />

                    <p className="mt-4 text-slate-400">
                      Generating AI Executive Report...
                    </p>

                  </div>
                </div>
              ) : (
                <div className="space-y-6">
                  {/* Executive Summary */}
                  <Card title="Executive Summary">
                    <div className="prose prose-invert max-w-none">

                      <ReactMarkdown>

                        {executiveSummary}

                      </ReactMarkdown>

                    </div>
                  </Card>

                  {/* Threat Assessment */}
                  <Card title="Threat Assessment">
                    <div className="prose prose-invert max-w-none">

                      <ReactMarkdown>
                        {threatAssessment}
                      </ReactMarkdown>
                    </div>
                  </Card>

                  {/* Business Impact */}
                  <Card title="Business Impact">
                    <div className="prose prose-invert max-w-none">
                      <ReactMarkdown
                      >
                        {businessImpact}
                      </ReactMarkdown>
                    </div>
                  </Card>

                  {/* Recommendations */}
                  <Card title="Recommendations">
                    <div className="prose prose-invert max-w-none">
                      <ReactMarkdown
                      >
                        {recommendations}
                      </ReactMarkdown>
                    </div>
                  </Card>

                  <Card title="Top Merchants">
                    <div className="space-y-3">
                      {report?.top_merchants?.length ? (
                        report.top_merchants.map((merchant, index) => (
                          <div
                            key={index}
                            className="flex justify-between items-center border-b border-slate-800 pb-2"
                          >
                            <span className="text-slate-300">
                              {merchant.merchant}
                            </span>
                            <span className="px-2 py-1 rounded-md bg-cyan-500/10 text-cyan-400 text-xs font-semibold">
                              {merchant.transactions}
                            </span>
                          </div>
                        ))
                      ) : (
                        <div className="text-slate-500 text-sm">
                          No merchant statistics available.
                        </div>
                      )}
                    </div>
                  </Card>

                  <Card title="High Risk Transactions">
                    {report?.high_risk_transactions?.length ? (
                      <div className="space-y-3">
                        {report.high_risk_transactions.map((tx) => (
                          <div
                            key={tx.transaction_id}
                            className="rounded-lg bg-slate-900 border border-slate-800 p-3"
                          >
                            <div className="flex justify-between">
                              <span className="font-mono text-cyan-400">
                                {tx.transaction_id}
                              </span>
                              <span className="text-red-400 font-semibold">
                                {tx.risk_level}
                              </span>
                            </div>
                            <div className="mt-2 text-sm text-slate-300">
                              Merchant: {tx.merchant_name}
                            </div>
                            <div className="text-sm text-slate-400">
                              Amount: ${tx.amount}
                            </div>
                            <div className="text-sm text-amber-400">
                              Risk Score: {tx.risk_score}
                            </div>
                          </div>
                        ))}
                      </div>
                    ) : (
                      <div className="rounded-lg border border-emerald-500/20 bg-emerald-500/10 p-4">
                        <div className="text-emerald-400 font-semibold">
                          ✅ No High Risk Transactions Found
                        </div>
                        <div className="text-sm text-slate-400 mt-1">
                          No transactions are currently classified as High or Critical risk.
                        </div>
                      </div>
                    )}
                  </Card>
                </div>
              )}
            </div>
          </Card>
        </div>
      </div>
    </DashboardLayout >
  );
}
