from app.services.gemini_service import generate_executive_report


async def build_ai_executive_report(data: dict):

    prompt = f"""
You are the AI Executive Intelligence Engine for FinGuard AI.

You are writing a report for a Chief Risk Officer (CRO), Fraud Operations Head, and executive leadership.

Analyze ONLY the supplied data.

Never invent:
- dates
- names
- analyst names
- departments
- organizations
- statistics not provided
- transaction counts not provided

Never add:
- greetings
- signatures
- placeholders like [Your Name]
- fictional assumptions

Write the report in clean GitHub Markdown.

Use exactly these sections:

# Executive Summary

# Threat Assessment

# Business Impact

# Recommendations

Keep the report concise, professional and factual.

Current Report Data

Generated At:
{data["generated_at"]}

Overall Risk:
{data["overall_risk"]}

Fraud Rate:
{data["fraud_rate"]}%

Total Transactions:
{data["total_transactions"]}

Fraud Transactions:
{data["fraud_transactions"]}

Top Merchants:
{data["top_merchants"]}

High Risk Transactions:
{data["high_risk_transactions"]}

Recommendations Generated By Rule Engine:
{data["recommendations"]}
"""

    try:

        return await generate_executive_report(prompt)

    except Exception as e:

        print(f"Gemini Report Error: {e}")

        return f"""
# Executive Summary

The AI report could not be generated because the Gemini service is temporarily unavailable or its request quota has been exceeded.

Overall Risk: **{data["overall_risk"]}**

Fraud Rate: **{data["fraud_rate"]}%**

Total Transactions: **{data["total_transactions"]}**

Fraud Transactions: **{data["fraud_transactions"]}**

# Threat Assessment

No AI-generated threat assessment is currently available.

# Business Impact

Core fraud analytics remain available and continue to provide reliable operational metrics.

# Recommendations

- Retry report generation after a short delay.
- Verify Gemini API quota and billing.
- Continue using dashboard analytics until AI reporting becomes available.
"""