import React from "react";
import {
  ShieldCheck,
  AlertTriangle,
  CheckCircle2,
  FileText,
  Shield,
  Activity
} from "lucide-react";

export function AIInvestigationPanel({ report }) {
  if (!report) {
    return (
      <div className="py-10 text-center text-slate-400">
        No investigation report available.
      </div>
    );
  }

  const investigation = report.investigation_report;

  return (
    <div className="space-y-6">

      {/* Header */}
      <div className="border-b border-slate-800 pb-4">
        <div className="flex items-center gap-2">
          <Shield className="w-5 h-5 text-cyan-400" />
          <h2 className="text-lg font-semibold text-slate-100">
            AI Investigation Report
          </h2>
        </div>

        <p className="text-xs text-slate-400 mt-1">
          Generated by FinGuard AI Investigation Engine
        </p>
      </div>

      {/* Executive Summary */}

      <div>
        <div className="flex items-center gap-2 mb-2">
          <FileText size={18} className="text-cyan-400" />

          <h3 className="font-semibold text-slate-100">
            Executive Summary
          </h3>
        </div>

        <div className="rounded-lg bg-slate-900 border border-slate-800 p-4">
          <p className="text-sm leading-6 text-slate-300">
            {investigation.summary}
          </p>
        </div>
      </div>

      {/* Risk Cards */}

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">

        <div className="rounded-xl bg-slate-900 border border-slate-800 p-5">

          <div className="text-xs uppercase tracking-wider text-slate-500">
            Risk Level
          </div>

          <div
            className={`mt-2 text-2xl font-bold ${
              investigation.risk_assessment.risk_level === "Low"
                ? "text-emerald-400"
                : investigation.risk_assessment.risk_level === "Medium"
                ? "text-amber-400"
                : "text-red-400"
            }`}
          >
            {investigation.risk_assessment.risk_level}
          </div>

        </div>

        <div className="rounded-xl bg-slate-900 border border-slate-800 p-5">

          <div className="text-xs uppercase tracking-wider text-slate-500">
            Risk Score
          </div>

          <div className="mt-2 text-2xl font-bold text-cyan-400">
            {investigation.risk_assessment.risk_score}
          </div>

        </div>

      </div>

      {/* Drivers */}

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">

        {/* Risk Drivers */}

        <div className="rounded-xl bg-slate-900 border border-red-500/20 p-5">

          <div className="flex items-center gap-2 mb-4">

            <AlertTriangle
              size={18}
              className="text-red-400"
            />

            <h3 className="font-semibold text-slate-100">
              Risk Drivers
            </h3>

          </div>

          <ul className="space-y-3">

            {investigation.positive_drivers.map((item, index) => (

              <li
                key={index}
                className="text-sm text-slate-300 leading-6"
              >
                • {item}
              </li>

            ))}

          </ul>

        </div>

        {/* Mitigation */}

        <div className="rounded-xl bg-slate-900 border border-emerald-500/20 p-5">

          <div className="flex items-center gap-2 mb-4">

            <ShieldCheck
              size={18}
              className="text-emerald-400"
            />

            <h3 className="font-semibold text-slate-100">
              Mitigating Factors
            </h3>

          </div>

          <ul className="space-y-3">

            {investigation.mitigating_factors.map((item, index) => (

              <li
                key={index}
                className="text-sm text-slate-300 leading-6"
              >
                • {item}
              </li>

            ))}

          </ul>

        </div>

      </div>

      {/* Recommendation */}

      <div className="rounded-xl border border-cyan-500/30 bg-cyan-500/10 p-5">

        <div className="flex items-center gap-2 mb-3">

          <CheckCircle2
            size={18}
            className="text-cyan-400"
          />

          <h3 className="font-semibold text-cyan-300">
            Recommendation
          </h3>

        </div>

        <p className="text-sm text-slate-200 leading-6">
          {investigation.recommendation}
        </p>

      </div>

      {/* Footer */}

      <div className="flex items-center justify-between border-t border-slate-800 pt-4">

        <div className="flex items-center gap-2 text-xs text-slate-500">

          <Activity size={14} />

          Generated using SHAP Explainability + FinGuard AI Rules Engine

        </div>

        <span className="text-xs font-semibold text-emerald-400">
          Investigation Complete
        </span>

      </div>

    </div>
  );
}